development:
  adapter: mysql2
  encoding: utf8
  database: finocomputer_development
  pool: 5
  username: root
  password: my123
  #host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: finocomputer_test
  pool: 5
  username: root
  password: my123
  #host: 127.0.0.1


